### PR TITLE
Add new Logos

### LINKED ISSUE #1: Have a logo

### PR DESCRIPTION
**Pull request by AdrianoCahete**
- Move the legacy logos to the `logo\legacy` folder
- Add the new logo `source`, `minified`, and `symbol` versions.
    - `source` is the original one, exported directly from Figma. it's the one that you need to use to make prints.
    - `minified` is after [SVGO](https://github.com/svg/svgo) optimization. Is the one that you need to use on the web.
    - `symbol` is to use when only the logo as a symbol is needed, like favicons.

Fixes #1

### CODE REVIEW

**Review by williamdes — APPROVED** [review]
Perfect!
I will merge this one
You could add the output of sha512 and sign the output with your GPG key that would be cool

But this is not very needed, I can provide you a command if you prefer

**Comment by AdrianoCahete** [comment]
> You could add the output of sha512 and sign the output with your GPG key that would be cool

Ok, found how to do this. Do I need to upload the sha512 file created to this PR? If yes, the commit is already signed, this counts?

> I can provide you a command if you prefer

Remember that I'm a windows user :P

**Comment by williamdes** [comment]
> If yes, the commit is already signed, this counts?

Oh sure, it counts but this is more portable and intended I think :)

You can add is as a text file on this PR

**Comment by williamdes** [comment]
Ah, I did not explain myself well :)
You can do this command (just an example)
```
sha512sum *.patch | gpg --clear-sign --armor -u williamdes@wdes.fr
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

b289f4fe3da1f269558aa22c844f374c3dd2bd4d90b9d12422b7b5e90f28950ba55e5ec092c2c2532398c25c3b7d37465802dd281c9543bb0f1f56c0957fb5aa  dash-negative-lineno.patch
-----BEGIN PGP SIGNATURE-----

iQJHBAEBCgAxFiEExNkf3872tKPGU/14kKDvG4JRqIkFAl/ZEgATHHdpbGxpYW1k
ZXNAd2Rlcy5mcgAKCRCQoO8bglGoic1+D/9UaYM8Xw7Ge2bi5Ytf1ygaSF6nytKh
pT71VEiLXMPxjS+rYedYEepAReniYgHfM2KSStOeA9qzNB2qYpmj0hJDpQmZvK17
hTQ12JfPOF4zF167dqwQYxdDJnsrI+ns/s3d4KyDw0z1/6cAwN1VdkDJp0c6qdvy
23XDWlO8RJtEPqkeXVeOq7IOr4CXSiFR+LviVEwjjrfpkYyNiJ6q5CtnTe0TF+p6
WRet3g3s9pYSIhTm8S6GesIPQuv4NdVxMhtplW6F1t49qoFykVAWcr7d7NjFbIu+
my6qc+QKCIvnfd80s3eDOV84pR4MplrOIbRsG0vvtQX/WOtf5XxTHPrn9KY4ZQgW
/x+Tgh+LPvF0z0sJin6WsCGVl06STnnxLTLTsdCpGUvmnGm/UYnUMLBiSyqspyWB
sSbRc1mvZlGLqoCrIx5JreJ7acu4JglrAY5sSNPN5MKtQAfVtxxTR564aKhgq0SD
SAnY1YkPWv+2lnnXKfL+yemhtxdiWri7HQsS7FaLM1Tx5/JP/fIPnHKlkAZt60St
Xlt1VUTTi+Mfc5OT0KFHrQMgw8mkQ8OXkt4SYJvwRqr4caVIWasc9m0jzM54bmJK
Kh5EDuS4KoeH92k2Rlad1bY0c/lu3MJ+EuS1TKiWQV8AMlKiAvhrVfi00Apyk5iz
KZ9X8d9vPI0YRg==
=lNCC
-----END PGP SIGNATURE-----
```

And here you will leave in a file some hashes nobody can discuss and they can be verified without git and for ever

Because the files you committed still can be changed and the history re-worked (that would remove your gpg signs on commits but still)

**Comment by AdrianoCahete** [comment]
I think it is it? Or I'm doing (another thing) wrong?

λ hash .\airballoon_logo_symbol-source.svg
2C32229D39EFF107F2A6234E081E9C56D9CFD2B9F2D0748133A818246908280A87110E61EC9418EE3B4B12002F1FA9E0E4796A01612A2D853B4FB9A2C8D2A6A1

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

2C32229D39EFF107F2A6234E081E9C56D9CFD2B9F2D0748133A818246908280A87110E61EC9418EE3B4B12002F1FA9E0E4796A01612A2D853B4FB9A2C8D2A6A1
-----BEGIN PGP SIGNATURE-----

iQJJBAEBCgAzFiEEoTWQEwTnE/46OddzMnDXOoo0PWQFAl/ZQMIVHG1lQGFkcmlh
bm9jYWhldGUuZGV2AAoJEDJw1zqKND1k4DMP/0xgKmNfuciSk95w+GojmsH39UGl
peq7ijDNw1yAoLp/R1hJfdL6DKpYk5nAicHs0C2gjMatP+0WxwzQkO4b29rEdhgO
rhsrKvPs+E1vLjdEGgWe6eWeRU/qpbdwif3jeI0rTOO8kjNdOK8/odqokVh9clpk
GhVDB1mTVpTENTartvmYnANM/JpxnXxDTXzthyIY2glSpxt0bx3d03IsvJHj8z8v
MF47qPMWUM75pSWKSe8VDlBE+OJcs8t7D3UHQ+J64m6MbVRn/slDVJwPBpicWCz0
G1wDbpao0NFJGGX68mU5PBjX1zHBwia3QIUWFxccVtkNMqbt0ZPEClpNa9r08TKq
f4GqnT/H/seKIy6jPmTs/TmWSkR+VdQ9Ps3H1coYMfZG9grGmUFJOX4fTGTHxjDA
apawGda5GL1cceBiFR/nwY9rAdFlsFSMly91K1PgALufnmcOWtIPR1f8qJbbhP00
SeIN6XImDQESqfCXl9aaeRmSxSxhWTK8qqFEBiK+NEIeSLa/1Jobi/60s3DuF0sJ
9iviV6y/k9I34TIB9ABoHGU13Olk91QrEhcdJne53RCdh56grqReRsZ1PZJsrERu
6Xu67Pl7FGuw67XplAMNjgqo5kMYWt1byw4WUSmpVdTD4+eT8VymK9nVXlDUCbSa
M9OeEkZ6ldu/HIi4
=LHG/
-----END PGP SIGNATURE-----
```

---

λ hash .\airballoon_logo-minified.svg
22B72652633F634AE784FC2D6EA2EFFB2759A258C9D1AB236DE23B2956210269801319AA61A552DAF8B83573EEAEA42D2430DBD7608BC89712B6A3002751697C

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

22B72652633F634AE784FC2D6EA2EFFB2759A258C9D1AB236DE23B2956210269801319AA61A552DAF8B83573EEAEA42D2430DBD7608BC89712B6A3002751697C
-----BEGIN PGP SIGNATURE-----

iQJJBAEBCgAzFiEEoTWQEwTnE/46OddzMnDXOoo0PWQFAl/ZQRwVHG1lQGFkcmlh
bm9jYWhldGUuZGV2AAoJEDJw1zqKND1kgtgP/RHf4svoVA1IB0hlMUSgnOU2KU7i
dXCn5fTf43Xpy996fdumaZpR/+QGEpjbaMDd+36UrN/hOsbNf/gc+Tv0Fk5ivb8p
cAKIiIa7qOHyCgclhlrx4L1jTm+MsN3UZ8G6sBV1+0wIZ3w+tF1//RvNct7CJMIR
kS+x8LFW6ULr8O20YvQidevSshAlg3sPVbb4nSRlq/WP9o+ahMYe3OvHMCQfNkpr
nqdeUATGa8O1y8ByZHezQ98rPcwxR3apLvT9rKL3AWB3ko7qf+5vNFo6gNcgDBst
koUm674aq+BqqUmmHHSEhdustcCdS3ahSAl61GZ4ABQxyK6PytsASQB6Srk67qOl
DeXL4YMXnKPhvblHRBY7ABfxz/QlL+Dxjy7Yjxy98innmpWwowd+JfLwNbHA2u/F
BBRNs3szCiZBJpdQmzXWCuhIdOkMlsHAV2Ip8v+HJBITiamtBNTHd4QOkCDFJgc2
O2xTc4630qzY+M9HPDdMiWp+OOkz3lPYGL6FKmCU1rejkF0LswZmzxoH6PbneUJv
N44FTeHQ144t3yhR6bBFC+oCoIHHrWG/jfXp1Se+TlmHPXUthRJbIeRbMhi83XLa
lJBhBxvZRwZc4kx65c7VXI4oxALI1uqXRkud0SFOlKzoQ0lroGjzjwNfXwplSBRn
iv+l0v+Jq3bC0AFl
=Vxlr
-----END PGP SIGNATURE-----
```

---

λ hash .\airballoon_logo-source.svg
CA20379E9B9C8148C6215B3DC543421AE849B35D754CE1773560AF55F3DFB1D3B402AB75C1EBEF87BFA8BAB44F069627C1CE40727312F9A74F509336EE17B845

```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

CA20379E9B9C8148C6215B3DC543421AE849B35D754CE1773560AF55F3DFB1D3B402AB75C1EBEF87BFA8BAB44F069627C1CE40727312F9A74F509336EE17B845
-----BEGIN PGP SIGNATURE-----

iQJJBAEBCgAzFiEEoTWQEwTnE/46OddzMnDXOoo0PWQFAl/ZRk4VHG1lQGFkcmlh
bm9jYWhldGUuZGV2AAoJEDJw1zqKND1kkzEP/RQNivVVVgFuZXXDwIo8btIjxZ1Y
Ay1Eg6239GPrQdAoHq+6VaIVRiuYd85S1000UmxQfcRPd7dHBMXpsVxf2KSv2jW6
y+9cRWpDsICCQUHBP4WkKrAPJk9rPIGakRUyoDsitc2iAyvr6Iv6uyHU+CMdvpsb
/VE7dqKmLd+JyeXBvTQ1ggeyjfhhLR23ka+LsQw2z/mVEuIsB24FgojOsBRIMZSW
5S33MSIo9NldqBAt8jfQThFe0ae0+Qk58SGWEojkOIsZ5hJEAN87wO7kEcJiPNF7
1Ww56zyy6zLJcNZhFUNi05rCBiizyPU0j984CZCO06PRdg+TZLGfB3xatS6NHHP0
W6FmhuEKKSyKfLyVkMEDxENaq5eO+MDPat8VNo+4M+Bf2AUJs16RzcN7rWY1IMrN
1x9dSssUZYTHUUbrr/m+yFnkWVwPFOZdCwKTgjZZ0+Ak42WQffjVd2ogx9lKMGdM
tZSyc/40182Pl6UmlrWPaMyocGCHkeHua2Z8xJwZT2y0US2xQx1U0pQqezEvgpUM
hq6iSthuCpZKN2LbkM+Sf9JtWsYbl4JYT9XS3bHsoKIvYvh1kjx9IABdqzEpoVT+
PKrfsbq2CxqDLY1rav3O/f+wEbFFmEPx+ZHvo4G6SLqRCTtMus6VbtARjLn9nb4u
oDz2FL/qEkUVmavu
=VFfv
-----END PGP SIGNATURE-----
```

**Comment by williamdes** [comment]
Hi,
I made it work for you :) 

Here is the text you should sign to seal your files.
I used sha512sum on Ubuntu.

```
22b72652633f634ae784fc2d6ea2effb2759a258c9d1ab236de23b2956210269801319aa61a552daf8b83573eeaea42d2430dbd7608bc89712b6a3002751697c  airballoon_logo-minified.svg
ca20379e9b9c8148c6215b3dc543421ae849b35d754ce1773560af55f3dfb1d3b402ab75c1ebef87bfa8bab44f069627c1ce40727312f9a74f509336ee17b845  airballoon_logo-source.svg
2c32229d39eff107f2a6234e081e9c56d9cfd2b9f2d0748133a818246908280a87110e61ec9418ee3b4b12002f1fa9e0e4796a01612a2d853b4fb9a2c8d2a6a1  airballoon_logo_symbol-source.svg
```

```
sha512sum *.svg | gpg --clear-sign --armor -u williamdes@wdes.fr
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

22b72652633f634ae784fc2d6ea2effb2759a258c9d1ab236de23b2956210269801319aa61a552daf8b83573eeaea42d2430dbd7608bc89712b6a3002751697c  airballoon_logo-minified.svg
ca20379e9b9c8148c6215b3dc543421ae849b35d754ce1773560af55f3dfb1d3b402ab75c1ebef87bfa8bab44f069627c1ce40727312f9a74f509336ee17b845  airballoon_logo-source.svg
2c32229d39eff107f2a6234e081e9c56d9cfd2b9f2d0748133a818246908280a87110e61ec9418ee3b4b12002f1fa9e0e4796a01612a2d853b4fb9a2c8d2a6a1  airballoon_logo_symbol-source.svg
-----BEGIN PGP SIGNATURE-----

iQJHBAEBCgAxFiEExNkf3872tKPGU/14kKDvG4JRqIkFAl/aBkkTHHdpbGxpYW1k
ZXNAd2Rlcy5mcgAKCRCQoO8bglGoic07D/0ViuOn3YQYzgxtjrtxfAzX65cqSSft
3HeLOxaPvzCUkCe15qsbxFTBkVWfUnkPSDVwc7vqU/L9y4zY7thUpYDHCU3y2TC3
XHW1c8WytJJ4TTzL7EOylP79XEMOPeef0/B2/6N8JyZSYqVC0MFXfnX+Yu7ffyRW
V8rkEUBnorlxtUhiraz/0AXklhMpE1qezFwCmLQ+Iw6L6rbtRVT3+OdmhndL7n+X
Mkh2A2OHdnRSq6NcL6FGUmTeksBInqQcTzp1vgXuwGBetIziyUNdEuexjywIkC6c
NJvBt8tyuf3pEsyF1K/p7dxVRuqTUBrZsoZsYtvZWX4mTm182K2yzI6QmhkHSYd9
EwnNGyBW7NX5NJICpHXNmQMEanlJ1tpeJNvCF8sLmja00GZjowwD2BJZbODGjgiQ
U56vlntcROStPPvGPZlhCGgldNuV1RuGDn1Jwmr/EWd0i1WIcNNq5XW7J6SnIW6P
TyNSM8ndQTk1ZQffyJ7WVRbkqjqAEuATnu2iVHK/a6PGvvcqE6vfw9aMKKdFyPLl
dxFLSjmBfVFEce8N/df428QQyRRugTnuqcNZJDDg2eNqWhj0rDZwaKoZrDl0mH5D
UbvKswvoDRQTdkHvph1hJ6f9X8qME4yB+KLcaPbcjTT3anmJnPo4Evg23PiUjQ+q
8hQ7s3Csg78AlQ==
=uXMs
-----END PGP SIGNATURE-----
```

PS: I know this is uncommon and maybe overkill but some signing practices is never too much and keeping the data intact is an interesting subject

**Review by williamdes — APPROVED** [review]

**Comment by AdrianoCahete** [comment]
```
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA512

22b72652633f634ae784fc2d6ea2effb2759a258c9d1ab236de23b2956210269801319aa61a552daf8b83573eeaea42d2430dbd7608bc89712b6a3002751697c  airballoon_logo-minified.svg
2c32229d39eff107f2a6234e081e9c56d9cfd2b9f2d0748133a818246908280a87110e61ec9418ee3b4b12002f1fa9e0e4796a01612a2d853b4fb9a2c8d2a6a1  airballoon_logo_symbol-source.svg
ca20379e9b9c8148c6215b3dc543421ae849b35d754ce1773560af55f3dfb1d3b402ab75c1ebef87bfa8bab44f069627c1ce40727312f9a74f509336ee17b845  airballoon_logo-source.svg
-----BEGIN PGP SIGNATURE-----

iQJJBAEBCgAzFiEEoTWQEwTnE/46OddzMnDXOoo0PWQFAl/aTsoVHG1lQGFkcmlh
bm9jYWhldGUuZGV2AAoJEDJw1zqKND1kbpUP/3K5XvojMhDvvbRRSBtSQW74SXfj
urH+UibVO6N3WKa9bxYXDnpz4gYT/XNqOTVDEOj+QFaeb1PuYsoK6xZtPt5J4S0g
DcqExfP8k0sPQYhSM9dWoX+PCxHqqcsm3AYjhh7p13WERqb+H+hBuTFiOydemUJa
+MIi2mUBStlJaPEIesXpFjdspbbwqm/C1GLyCZA4IU0SobT93UR0JUaCVoxCztvr
kVCpl5Xj34+dcoygECw8dAEou1XpQoD/8E5sTcMhw3zBIGNR1REdSJrJqwmseBap
pUvwVQVKrSTkr19ZxKbiKCEnKsGmGb6+c9Oaz78WcNieQez6etk2kdpwtDvrk8Os
2X57eeOcGX1IWjuPG1Nn/bGAITV4VSG02Pf3r7J9BoThx3dDB2mRDl065RCUa8wG
hn/DU/hUdO/kA3kxUIyp1rno+MraxmZOSPvNrCMsnDVcMMwzVE1sAbzADPpi0oPA
AeodrsZh9Ept+VJQQsuYzJrlh4MxKirCdp50dV7/YPxia6wORusgVparQgc3MaBV
KJnhM4Rg0TvfKzBRLWuUm9IkbmIvTnzGcUzglfsP6iKsJWbiANGCYnR27GBei59G
wWXut+m85WV9E0tz9AfFCbxYWKz3YLZL6UEep58jRDjHMe+skFeXhHGcYVn/NDpo
ktoHdiRIa/7qK3yl
=1Wfi
-----END PGP SIGNATURE-----
```

**Comment by williamdes** [comment]
Merged, thank you ! :100:

**Comment by williamdes** [comment]
Hi @AdrianoCahete 

I am very sorry about something, I hope you will understand my feeling more than I can. The previous logo always was coming back to me, like a memory, something lost. In the end I felt bad about the logo change, I will never fully know why..
So this commit was made, and I added some comments about this in the description: 1639194c45009d35a92dab8f55cf8632f3e93581

I am and will always be grateful for the work on the logo v2. To keep transparency, I leave you this message. Sure I could have silenced this revert but that would not have been something good.

**Comment by AdrianoCahete** [comment]
NP, it's your project after all! :)

**Pull request merged**
